/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface AdlDateComponent {
    'day': string;
    'month': string;
    'year': string;
  }
}

declare global {


  interface HTMLAdlDateComponentElement extends Components.AdlDateComponent, HTMLStencilElement {}
  var HTMLAdlDateComponentElement: {
    prototype: HTMLAdlDateComponentElement;
    new (): HTMLAdlDateComponentElement;
  };
  interface HTMLElementTagNameMap {
    'adl-date-component': HTMLAdlDateComponentElement;
  }
}

declare namespace LocalJSX {
  interface AdlDateComponent extends JSXBase.HTMLAttributes<HTMLAdlDateComponentElement> {
    'day'?: string;
    'month'?: string;
    'year'?: string;
  }

  interface IntrinsicElements {
    'adl-date-component': AdlDateComponent;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


